name: tests

on: [push]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.11", "3.12", "3.13", "3.14"]
        include:
          - os: windows-latest
            python-version: "3.14"
          - os: macos-latest
            python-version: "3.14"

    continue-on-error: ${{ matrix.os != 'ubuntu-latest' }}

    steps:
    - uses: actions/checkout@v4
    - name: Set up uv
      uses: astral-sh/setup-uv@v6
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: uv sync --all-groups
    - name: Test with pytest
      run: uv run pytest
